/*

 +---------------------------------+
 | MOM Customer Sales Order Export | MOM v6.2 -> CB 13.2
 +---------------------------------+-------------------------------+
 | Sanitizes and translates between MOM and CB database structures |
 +-----------------------------------------------------------------+

 */

SELECT

PaymentTermCode
ShippingMethodCode
ShippingMethodGroup
ShipToCode
SalesOrderCode
BillToCode
ShippingDate
LatestShipDate
ExchangeRate
Type
ApplyTo
ARAccountCode
BillToCountry
BillToPostalCode
ContactCode
CouponCode
CouponType
DiscountAccountCode
DiscountType
FreightAccountCode
FreightTaxCode
OpportunityCode
OtherAccountCode
OtherTaxCode
PaymentTermGroup
ReceivableCode
ShipToCountry
ShipToName
ShipToPostalCode
SourceCode
WarehouseCode
SourceSalesOrderCode
RootDocumentCode
SalesOrderDate
ProjectCode
BillToName
SubTotal
SubTotalRate
Freight
FreightRate
FreightTax
FreightTaxRate
Tax
TaxRate
Total
TotalRate
POCode
SalesRepOrderCode
PODate
DueDate
CancelDate
AmountPaid
AmountPaidRate
IsPaid
DaysBeforeInterest
DiscountableDays
DiscountPercent
InterestPercent
DueType
StartDate
DatePaid
OrderStatus
BillToAddress
BillToCity
BillToState
BillToCounty
BillToPhone
BillToPhoneExtension
ShipToAddress
ShipToCity
ShipToState
ShipToCounty
ShipToPhone
ShipToPhoneExtension
CurrencyCode
IsProcessed
IsAllowBackOrder
Balance
BalanceRate
AppliedCredit
AppliedCreditRate
Discount
DiscountRate
WriteOff
WriteOffRate
Other
OtherRate
OtherName
OtherTax
OtherTaxRate
Notes
IsVoided
IsOnHold
IsPrinted
IsOrderAcknowledged
IsFromContract
RecurDocumentCode
PrintCount
CouponID
CouponDiscount
CouponDiscountRate
CouponDiscountType
CouponDiscountPercent
CouponDiscountAmount
CouponUsage
CouponDiscountIncludesFreeShipping
CouponRequiresMinimumOrderAmount
IsFreightOverwrite
WebSiteCode
WaveCode
SourceType
POSWorkstationID
POSClerkID
DownloadEmailSentDate
RootOrderCode
DateShipped
IsShipped
SaveCounterID
CouponComputation
TaxGroup1
TaxGroup1Rate
TaxGroup2
TaxGroup2Rate
TaxGroup3
TaxGroup3Rate
MerchantOrderID_DEV000221
PaymentFailedEmailSent_DEV000221
SourceFeedbackMessage_DEV000221
SourceFeedbackType_DEV000221
IsCBN
CBNPO
CBNSO
CBNState
InternalNotesCode
InternalNotesDescription
InternalNotes
PublicNotesCode
StoreMerchantID_DEV000221
PublicNotesDescription
PublicNotes
ReturnedSubTotal
ReturnedSubTotalRate
ReturnedTax
ReturnedTaxRate
IsPickUp
BillToAddressType
ShipToAddressType
WarehouseAddressType
IsBlindShip
IsFreightQuoted
Signature
SignatureSVG
CBNMasterID
BillToPlus4
ShipToPlus4